<?php

namespace Recon\Tests;

use Illuminate\Support\Facades\Http;
use Orchestra\Testbench\TestCase as Orchestra;
use Recon\ReconFacade;
use Recon\ReconServiceProvider;
use Recon\Tests\Models\TestModelItem;

class BaseTest extends Orchestra
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->loadMigrationsFrom(__DIR__ . '/Models/migrations');

        ReconFacade::partialMock()->shouldReceive('detectModelPath')->andReturn(__DIR__ . '/Models');
        ReconFacade::partialMock()->shouldReceive('detectModelNamespace')->andReturn('Recon\\Tests\\Models');
    }

    protected function getPackageProviders($app)
    {
        return [ReconServiceProvider::class];
    }
}
