<?php

namespace LaravelMl\Tests;

use Illuminate\Http\Client\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;
use LaravelMl\Api;
use LaravelMl\LaravelMlFacade;
use LaravelMl\LmlDatabaseConfig;
use LaravelMl\Tests\Models\TestModelItem;

class DatabaseSyncCommandTest extends BaseTest
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        config([
            'laravel-ml' => [
                'databases' => [
                    LmlDatabaseConfig::make()
                        ->setName('test_models')
                        ->setType(LmlDatabaseConfig::TYPE_ANOMALY)
                        ->setDatatype(LmlDatabaseConfig::DATATYPE_CONTINUOUS)
                ]
            ],
        ]);
    }


    /** @test */
    public function modelShowsAnErrorWhenNoApiKey()
    {
        $this->artisan('ml')
            ->expectsOutput('Missing API Key. Add ML_API_TOKEN={apiKey} to your .env file. You can get a key at https://laravelml.com')
            ->assertExitCode(1);
    }

    /** @test */
    public function modelFailsCalmlyWhenNoDetectedModelsExist()
    {
        config([ 'laravel-ml.token' => 'abc']);

        LaravelMlFacade::shouldReceive('detectDatabases')->andReturn(collect());

        $this->artisan('ml')
            ->expectsOutput('No Laravel ML databases detected. Did you set it up correctly?')
            ->assertExitCode(1);
    }

    /** @test */
    public function modelMlCommandHandlesInvalidModel()
    {
        config([ 'laravel-ml.token' => 'abc']);

        $this->artisan('ml')
            ->expectsQuestion('Which ML Record Definition would you like to work with?', 'test')
            ->expectsOutput('Invalid choice. Please try again.')
            ->assertExitCode(1);
    }

    /** @test */
    public function modelMlCommandHandlesInvalidCommand()
    {
        config([ 'laravel-ml.token' => 'abc']);

        $modelName = (new TestModelItem())->ml()->database()->name();

        Http::fake([
            '*' => Http::response([], 404),
        ]);

        $this->artisan('ml')
            ->expectsQuestion('Which ML Record Definition would you like to work with?', $modelName)
            ->expectsOutput("Database does not exist yet.")
            ->expectsQuestion("Which action would you like to perform on {$modelName}?", 'test')
            ->expectsOutput('Invalid choice. Please try again.')
            ->assertExitCode(1);
    }

    /** @test */
    public function modelCreateModel()
    {
        config([ 'laravel-ml.token' => 'abc']);

        $recordConfig = (new TestModelItem())->ml();
        $modelName = $recordConfig->database()->name();
        $type = $recordConfig->database()->type();
        $datatype = $recordConfig->database()->datatype();

        Http::fake([
            Api::HOST . '/databases/' . $modelName => Http::response([], 404),
            Api::HOST . '/databases' => Http::response([
                'data' => [
                    'type' => $type,
                    'name' => $modelName,
                ]
            ], 200),
        ]);

        $this->artisan('ml')
            ->expectsQuestion('Which ML Record Definition would you like to work with?', $modelName)
            ->expectsOutput("Database does not exist yet.")
            ->expectsQuestion("Which action would you like to perform on {$modelName}?", 'Create')
            ->expectsQuestion("Detected type: {$type} ({$datatype}). Is this correct?", 'yes')
            ->assertExitCode(0);

        Http::assertSent(function (Request $request) use ($modelName, $type, $datatype) {
            return Str::contains($request->url(), ['/api/databases'])
                && $request->method() === 'POST'
                && $request['name'] === $modelName
                && $request['type'] === $type
                && $request['datatype'] === $datatype;
        });
    }

    /** @test */
    public function modelSyncDatabase()
    {
        config([ 'laravel-ml.token' => 'abc']);

        $recordConfig = (new TestModelItem())->ml();
        $modelName = $recordConfig->database()->name();
        $type = $recordConfig->database()->type();

        Http::fake([
            '*' => Http::response([
                'data' => [
                    'name' => $modelName,
                    'type' => $type,
                ],
            ], 200),
        ]);

        $existingModel = TestModelItem::create([
            'name' => 'zach',
            'age' => 25,
            'salary' => 50000,
        ]);
        $this->artisan('ml')
            ->expectsQuestion('Which ML Record Definition would you like to work with?', $modelName)
            ->expectsQuestion("Which action would you like to perform on {$modelName}?", 'Sync')
            ->assertExitCode(0);

        Http::assertSent(function (Request $request) use ($modelName, $existingModel) {
            return Str::contains($request->url(), ["/api/databases/{$modelName}/train"])
                && $request->method() === 'POST'
                && sizeof($request['samples']) === 1
                && $request['samples'][0]['features'][0] === 25
                && $request['samples'][0]['label'] === 50000
                && $request['samples'][0]['class'] === 'TestModel'
                && $request['samples'][0]['identifier'] === $existingModel->id;
        });
    }

    /** @test */
    public function modelDeleteDatabase()
    {
        config([ 'laravel-ml.token' => 'abc']);

        $modelName = (new TestModelItem())->ml()->database()->name();

        Http::fake([
            Api::HOST . '/databases/' . $modelName => Http::sequence()
                ->pushStatus(404) // the SHOW
                ->pushStatus(200), // the DELETE
        ]);

        $this->artisan('ml')
            ->expectsQuestion('Which ML Record Definition would you like to work with?', $modelName)
            ->expectsOutput("Database does not exist yet.")
            ->expectsQuestion("Which action would you like to perform on {$modelName}?", 'Delete')
            ->expectsQuestion("Are you sure you want to delete this database? This cannot be undone.", 'yes')
            ->assertExitCode(0);

        Http::assertSent(function (Request $request) use ($modelName) {
            return Str::contains($request->url(), ['/api/databases/' . $modelName])
                && $request->method() === 'DELETE';
        });
    }

}
