<?php

namespace LaravelMl\Tests;

use Illuminate\Http\Client\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;
use LaravelMl\LmlDatabaseConfig;
use Orchestra\Testbench\TestCase;
use LaravelMl\LaravelMlFacade;
use LaravelMl\LaravelMlServiceProvider;
use LaravelMl\Tests\Models\TestModelItem;

class RecordAssociationTest extends BaseTest
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        config([
            'laravel-ml' => [
                'databases' => [
                    LmlDatabaseConfig::make()
                        ->setName('test_models')
                        ->setType(LmlDatabaseConfig::TYPE_ANOMALY)
                        ->setDatatype(LmlDatabaseConfig::DATATYPE_CONTINUOUS)
                ]
            ],
        ]);
    }

    /** @test */
    public function recordAssociation()
    {
        Http::fake([
            '*' => Http::response([
                'data' => [],
            ], 200),
        ]);

        $testModel1 = TestModelItem::create([
            'name' => 'zach',
            'age' => 25,
            'salary' => 50000,
        ]);
        $testModel2 = TestModelItem::create([
            'name' => 'zach',
            'age' => 25,
            'salary' => 50000,
        ]);

        $response = $testModel1->associate($testModel2, 4.45, '::description::');

        $this->assertNotNull($response);

        Http::assertSent(function (Request $request) use ($testModel1, $testModel2) {
            return Str::contains($request->url(), ['/api/databases/' . $testModel1->ml()->database()->name() . '/records/' . $testModel1->ml()->networkId() . '/associate/' . $testModel2->ml()->networkId()])
                && $request->method() === 'POST'
                && $request['weight'] === 4.45
                && $request['description'] === '::description::';
        });
    }
}
