<?php

namespace LaravelMl\Tests\Interactions;

use Illuminate\Http\Client\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;
use Illuminate\Testing\Assert;
use LaravelMl\Helpers\InteractionBuilder;
use LaravelMl\Tests\BaseTest;
use LaravelMl\Tests\Models\TestModelItem;

class InteractionBuilderTest extends BaseTest
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        config([
            'laravel-ml' => [
                'database' => '::database::',
            ]
        ]);
    }

    // defaults
    /** @test */
    public function interactionBuilderWillSendHttpRequestDefault()
    {
        Http::fake();

        Session::shouldReceive('getId')->andReturn('abc');

        $interaction = (new InteractionBuilder('click'));
        $interactionResponse = $interaction->send();

        Http::assertSent(function (Request $request) use ($interaction) {
            return Str::contains($request->url(), ['/api/databases/::database::/interactions'])
                && $request->method() === 'POST'
                && $request['interactions'][0]['session_id'] === 'abc'
                && $request['interactions'][0]['type'] === 'click'
                && $request['interactions'][0]['uid'] === null
                && $request['interactions'][0]['timestamp'] === $interaction->timestamp
                && $request['interactions'][0]['value'] === null
                && $request['interactions'][0]['iid'] === null
                && $request['interactions'][0]['impressions'] === null
                && $request['interactions'][0]['metadata'] === null
                && $request['interactions'][0]['recommendation_id'] === null;
        });
    }

    // custom
    public function interactionBuilderWillSendHttpRequestCustom()
    {
        Http::fake();

        Session::shouldReceive('getId')->andReturn('abc');

        $interaction = (new InteractionBuilder('click'))
            ->setImpressions([154, '134']) // can it be int and string? packing 2 tests in 1. I know they say you shouldn't do it.
            ->setValue(14.5)
            ->setTimestamp(now()->midDay())
            ->setUserId(1534)
            ->setItemId(9423)
            ->setSessionId('::session::')
            ->setAction('::action::')
            ->setRecommendationId('::rec_id::')
            ->setMetadata([
                'duration' => 156,
                'genres' => 'Trap|Wrap|Many',
            ]);
        $interactionResponse = $interaction->send();

        Http::assertSent(function (Request $request) use ($interaction) {
            return Str::contains($request->url(), ['/api/databases/::database::/interactions'])
                && $request->method() === 'POST'
                && $request['interactions'][0]['session_id'] === '::session::'
                && $request['interactions'][0]['type'] === '::action::'
                && $request['interactions'][0]['timestamp'] === now()->midDay()->timestamp
                && $request['interactions'][0]['value'] === 14.5
                && $request['interactions'][0]['iid'] === 9423
                && $request['interactions'][0]['uid'] === 1534
                && $request['interactions'][0]['impressions'] === [154, '134']
                && $request['interactions'][0]['metadata'] === [
                    'duration' => 156,
                    'genres' => 'Trap|Wrap|Many',
                ]
                && $request['interactions'][0]['recommendation_id'] === "::rec_id::";
        });
    }
}
