<?php

namespace LaravelMl\Tests\Commands;

use Illuminate\Http\Client\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;
use LaravelMl\Api\Api;
use LaravelMl\Api\ApiFacade;
use LaravelMl\Tests\BaseTest;
use LaravelMl\Tests\Models\TestModelItem;

class DatabaseSeedCommandTest extends BaseTest
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        config([
            'laravel-ml' => [
                'database' => '::database::',
            ],
        ]);
    }

    /** @test */
    public function makesNetworkCallUsingDefault()
    {
        config([
            'laravel-ml' => [
                'token' => 'abc',
                'database' => '::database1::',
            ],
        ]);

        ApiFacade::shouldReceive('seedDatabase')->with('::database1::');

        Artisan::call('ml:seed');
    }

    /** @test */
    public function allDatabaseParamFromUserInputWillOverrideDefaultDatabase()
    {
        config([
            'laravel-ml' => [
                'token' => 'abc',
                'database' => '::database1::',
            ],
        ]);

        ApiFacade::shouldReceive('seedDatabase')->with('::database2::');

        Artisan::call('ml:seed', [
            '--database' => '::database2::',
        ]);
    }

}
