<?php

namespace Recon\Tests\Commands;

use Illuminate\Http\Client\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;
use Recon\Api\Api;
use Recon\Api\ApiFacade;
use Recon\Tests\BaseTest;
use Recon\Tests\Models\TestModelItem;

class ReconRetrainCommandTest extends BaseTest
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        config([
            'recon' => [
                'database' => '::database::',
            ],
        ]);
    }

    /** @test */
    public function makesNetworkCallUsingDefault()
    {
        config([
            'recon' => [
                'token' => 'abc',
                'database' => '::database1::',
            ],
        ]);

        Http::fake();

        Artisan::call('recon:retrain');

        Http::assertSent(function (Request $request) {
            return Str::contains($request->url(), ['/api/databases/::database1::'])
                && $request->method() === 'PUT'
                && $request['retrain'] === true;
        });
    }

    /** @test */
    public function allDatabaseParamFromUserInputWillOverrideDefaultDatabase()
    {
        config([
            'recon' => [
                'token' => 'abc',
                'database' => '::database1::',
            ],
        ]);

        Http::fake();

        Artisan::call('recon:retrain', [
            '--database' => '::database2::',
        ]);

        Http::assertSent(function (Request $request) {
            return Str::contains($request->url(), ['/api/databases/::database2::'])
                && $request->method() === 'PUT'
                && $request['retrain'] === true;
        });
    }

}
